---
title: "House Elections Overview"
author: "Chris Whaley"
output: 
  html_document: 
    keep_md: yes
date: "2022-11-14"
---

```{r, echo=FALSE}
library(USAboundaries)
library(sf)
library(tmap)
library(tidyverse)
library(here)

# interactive map view
tmap_mode("view")

# get and clean data
source(here("code", "02_clean.R"))

congress <- us_congressional()
house_votes_2020 <- house_votes %>% 
  dplyr::filter(year == 2020 & stage == "GEN") %>% 
  group_by(year, state, state_po, state_fips, office, district, totalvotes) %>% 
  mutate(winning_votes = max(candidatevotes),
         party_winner = if_else(candidatevotes == winning_votes, party, ''),
         winner_vote_pct = winning_votes/totalvotes
  ) %>% 
  ungroup() %>% 
  dplyr::filter(party_winner != '')

house_map_2020 <- congress %>% 
  left_join(house_votes_2020, by = c("state_abbr" = "state_po",
                                     "cd116fp" = "district"))

house_map_2020 <- st_as_sf(house_map_2020, crs = st_crs(congress))
```

House Elections in 2020
```{r eval=TRUE}
house_map <- tm_shape(house_map_2020) +
  tm_borders() +
  tm_fill(col = "party_winner", palette = "-Set1",
          id = "namelsad",
          popup.vars = c("Party winner: " = "party_winner", 
                         "Candidate votes: " = "candidatevotes",
                         "Total votes in district: " = "totalvotes",
                         "Vote percentage: " = "winner_vote_pct")
  )
house_map
```

